let camposCriados=[],campoSelecionado=null;function selecionarCampo(e){document.querySelectorAll(".campo").forEach(e=>e.classList.remove("selecionado")),e.classList.add("selecionado"),campoSelecionado=e;let t=e.querySelector(".nomeCampo").value;e.querySelector(".deCampo").value,e.querySelector(".tamanhoCampo").value;let a=document.getElementById("formularioPreenchimento");a.innerHTML=`
        <h3>${t}</h3>
        <textarea placeholder="Digite ou cole os valores para ${t} (um por linha)"></textarea>
    `;let o=a.querySelector("textarea");o.value=e.dataset.valor||"",o.addEventListener("input",function(){e.dataset.valor=o.value}),document.getElementById("abaContent").classList.remove("hidden")}function atualizarFormularioPreenchimento(){let e=document.querySelectorAll(".campo"),t=document.getElementById("gerarTxt"),a=document.getElementById("previewTxt");t.disabled=0===e.length,a.disabled=0===e.length,verificarTamanhoPreenchido()}function verificarTamanhoPreenchido(){let e=document.querySelectorAll(".campo"),t=!0;e.forEach(e=>{let a=e.querySelector(".tamanhoCampo");a.value?a.placeholder="Tamanho":(t=!1,a.placeholder="Tamanho obrigat\xf3rio")});let a=document.getElementById("previewTxt"),o=document.getElementById("gerarTxt");a.disabled=0===e.length||!t,o.disabled=0===e.length||!t}document.getElementById("novoCampo").addEventListener("click",function(){let e=document.getElementById("campos"),t=document.createElement("div");t.className="campo",t.innerHTML=`
        <input type="text" placeholder="Nome do Campo" class="nomeCampo">
        <input type="number" placeholder="A partir" class="deCampo">
        <input type="number" placeholder="Tamanho" class="tamanhoCampo">
        <button class="excluirCampo">Excluir</button>
    `,e.appendChild(t),atualizarFormularioPreenchimento(),verificarTamanhoPreenchido()}),document.addEventListener("click",function(e){e.target.classList.contains("excluirCampo")?(e.target.parentElement.remove(),atualizarFormularioPreenchimento(),verificarTamanhoPreenchido()):e.target.closest(".campo")&&selecionarCampo(e.target.closest(".campo"))}),document.getElementById("toggleAba").addEventListener("click",function(){let e=document.getElementById("abaContent"),t=document.querySelector(".aba-header .seta");e.classList.toggle("hidden"),t.textContent=e.classList.contains("hidden")?"▶":"▼"}),document.addEventListener("input",function(e){e.target.classList.contains("tamanhoCampo")&&verificarTamanhoPreenchido()}),document.getElementById("previewTxt").addEventListener("click",function(){let e=document.getElementById("previewTxtContent"),t=document.querySelectorAll(".campo"),a="",o=Array.from(t).map(e=>(e.dataset.valor||"").split("\n")),n=o[0].length;for(let l=0;l<n;l++){let r="",i=1;t.forEach((e,t)=>{let a=parseInt(e.querySelector(".deCampo").value),n=parseInt(e.querySelector(".tamanhoCampo").value),c=a+n-1,d=o[t][l]||"";i<a&&(r+="X".repeat(a-i),i=a);let m=d.padEnd(n," ").substring(0,n);r+=m,i=c+1}),a+=r+"\n"}e.textContent=a,document.getElementById("previewContainer").classList.remove("hidden")}),document.getElementById("gerarTxt").addEventListener("click",function(){let e=document.querySelectorAll(".campo"),t="",a=Array.from(e).map(e=>(e.dataset.valor||"").split("\n")),o=a[0].length;for(let n=0;n<o;n++){let l="",r=1;e.forEach((e,t)=>{let o=parseInt(e.querySelector(".deCampo").value),i=parseInt(e.querySelector(".tamanhoCampo").value),c=o+i-1,d=a[t][n]||"";r<o&&(l+="X".repeat(o-r),r=o);let m=d.padEnd(i," ").substring(0,i);l+=m,r=c+1}),t+=l+"\n"}if(t){let i=new Blob([t],{type:"text/plain"}),c=document.createElement("a");c.href=URL.createObjectURL(i),c.download="arquivo.txt",c.click()}}),document.addEventListener("DOMContentLoaded",function(){document.getElementById("previewTxt").disabled=!0,document.getElementById("gerarTxt").disabled=!0,verificarTamanhoPreenchido()});
